name: CI

on:
  pull_request:
    branches: [ master, dashboard ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pytest pytest-asyncio
          if [ -f dashboard/tests/requirements-test.txt ]; then pip install -r dashboard/tests/requirements-test.txt; fi
      - name: Run lint
        run: |
          echo "Run lint (placeholder). Add black/flake8 commands here."
      - name: Run tests
        run: |
          pytest -q
